### ISSUE TITLE
Any plans for dropping PHP < 5.3 support

### ISSUE THREAD

**Issue by usox** [phptal/PHPTAL#38]
Hi there

Just a quick question: Do you have any plans dropping the support for php < 5.3 in future releases? I'm going to write a patch (at least I'll try) which add Namespaces and Interfaces which will break the compatibilty to the current supported versions of php (php 5.1.x?).

**Comment by potherca** [comment]
@Ocramius Do you think we should take a stab at this? Maybe set up a v2 branch?

**Comment by Ocramius** [comment]
@potherca only if v2 deprecates installation methods that are not composer-based.

If we can switch to composer-only, then we can upgrade PHP version requirements gradually, as it doesn't consist in a BC break (users will simply be given an older compatible version).

If v2 lands with other installation methods, then every PHP version requirement bump will result in a BC break instead :-(

**Comment by potherca** [comment]
I am all for composer-only install. I've taken the liberty of [summarising what I think need doing for the README file](./41). We could define more things that we think/feel need to be improved and set a v2 milestone?

**Comment by Ocramius** [comment]
@potherca track everything you want to get done for a v2 in issues, then set the milestone (created [v2.0.0](https://github.com/phptal/PHPTAL/milestones)) and find people who can get those done for you :)

**Comment by Ocramius** [comment]
Also: I suggest keeping v2 very minimal (removing features/cleanups, mostly) in order to get some swing for working on new functionality (v2.* or v3).
Don't try adding stuff, or you'll be stuck quicker than ever.

**Comment by potherca** [comment]
Agreed. The main focus for me would be on cleanup/docs (to get a firm grasp of the current state of things) and removing things that are marked deprecated (either in TAL or in PHP) to be more "future proof".

Having a clean baseline should also help get some more people on board when I start promoting PHPTAL more widely in my personal network...

**Comment by usox** [comment]
@potherca If you need some help regarding the docs/cleanup, tell me.

**Comment by potherca** [comment]
@usox Feel free to comment on  issue #41 if you think I missed anything (or have further suggestions).

**Comment by Potherca** [comment]
@Ocramius Not sure whether we should close this issue (as PHP 5.3 is no longer supported) or rename it to "Start using namespaces" as that seems to be more what this thread is about. Ideas?

**Comment by Ocramius** [comment]
Let's just close this 👍
