### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by pornel** [phptal/PHPTAL#40]
I haven't done much PHPTAL work in recent years, and currently I'm focused on completely different projects.

I still think it's the best templating language for PHP. The code is good and stable.

Is anybody interested in taking over the project?

**Comment by potherca** [comment]
I am.

**Comment by pornel** [comment]
Great! Thanks, @potherca. I've moved the repository to a separate org, added existing collaborators, and added you as an owner.

**Comment by potherca** [comment]
Cool! :+1: 
I'm of to [WeCamp](http://weca.mp/) the coming week but I'll look into the open issues and chatting with the other maintainers when I get back.

**Comment by potherca** [comment]
@Ocramius and [I](/Potherca) have been appointed maintainers by @pornel for the time being.
Other people that are interested can still comment here but for now I am closing this issue.

**Comment by Ocramius** [comment]
@potherca note that I don't have deep insights on the repo sources, but I can help out :-)

**Comment by potherca** [comment]
Duly noted :+1:
