### ISSUE TITLE
Make phptal_lint install in the composer bin folder

### ISSUE THREAD

**Issue by REBELinBLUE** [phptal/PHPTAL#46]
Would it be possible to have PHPTAL_Lint install in the composer bin folder like phpcs, phpmd, phpunit etc do?

I can make a PR if you want, I just wanted to check there were no objections before I do?

**Comment by Ocramius** [comment]
@REBELinBLUE send a PR :-)

**Comment by potherca** [comment]
:+1:

**Comment by REBELinBLUE** [comment]
👍 OK, will take a look over the weekend

**Comment by Ocramius** [comment]
Handled in #47
