### ISSUE TITLE
EQQ/NEE

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [phptal/PHPTAL#93]
Good to see PHPTAL is still releasing new versions! 
I have a small feature suggestion that looks like something easy to implement - to add `EQQ` (`===`) and `NEE` (`!==`) operators. I've just found it missing when using `x EQ false` on a value that can be `true|false|null`, obviously I used `===` directly to make it work but new operators would complement the existing ones.

**Comment by Ocramius** [comment]
Do send patches: as long as something is well tested and documented, I would totally merge + release :-)
